project_id = "tvmvkjoubttuqnlkdciv"

[functions."delete-account"]
verify_jwt = false

[functions."submit-feedback"]
verify_jwt = false

[functions."create-payment-order"]
verify_jwt = false

[functions."verify-payment"]
verify_jwt = false

[functions."cancel-payment-order"]
verify_jwt = false

[functions."create-donation-order"]
verify_jwt = false

[functions."verify-donation-payment"]
verify_jwt = false
